apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt-spring-integration-node-client
  name: mqtt-spring-integration-node-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-spring-integration-node-client
  strategy: {}
  template:
    metadata:
      labels:
        app: mqtt-spring-integration-node-client
    spec:
      containers:
      - image: luksrn/mqtt-spring-integration-node-cli
        name: mqtt-spring-integration-node-cli
        resources: {}
status: {}
