apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mqtt-spring-integration-node-backend
  name: mqtt-spring-integration-node-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mqtt-spring-integration-node-backend
status:
  loadBalancer: {}
