apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pushgateway
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pushgateway
    spec:
      containers:
      - image: prom/pushgateway
        name: pushgateway
        resources: {}        
status: {}
